

import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider, useTheme } from "./theme";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { SessionProvider } from "next-auth/react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };



export default function RootLayout({ children, session }) {
  return (
    <SessionProvider session={session}>
    <html lang="en">
  
      <ThemeProvider>

          {/* Bungkus children dengan ThemeProvider */}
          {children}
          {/* Tambahkan ToastContainer */}
          <ToastContainer position="top-right" autoClose={3000} />
       
      </ThemeProvider>
   
    </html>
    </SessionProvider>
  );
}
